language:
  python

python:
  - "2.7"

env:
  - DJANGO=1.7.8
  - DJANGO=1.8.7

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install django==$DJANGO --quiet
  - pip install -r dev_requirements.dev --quiet

script:
  - cd test_project && ./runtests.sh

